---
title: "Bcell PHX postprocessing"
author: "Jonas Fischer"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
require(ggplot2)
require(ggthemes)
library(ggrepel)
require(viridis)
require(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(pathview)
```

## B cell GRN analysis

loading learned gene--gene associations of PHOENIX

```{r bcell data}
weights <- read.table('D_full.csv', header=T, sep=',', stringsAsFactors=T)
```

analysis cause-centered (aggregation of regulatory impact for input genes)

```{r bcell TF ana}

w_input_control <- setNames(rep(NA,length(unique(weights$from))),unique(weights$from))
for (i in 1:length(w_input_control))
{
  if (i %% 500 == 0)
  { print(i) }
  w_input_control[i] <-  sum(abs(weights$control[weights$from == names(w_input_control)[i]]))
}

w_input_treated <- setNames(rep(NA,length(unique(weights$from))),unique(weights$from))
for (i in 1:length(w_input_treated))
{
  if (i %% 500 == 0)
  { print(i) }
  w_input_treated[i] <-  sum(abs(weights$treated[weights$from == names(w_input_treated)[i]]))
}


## do differential
sum(names(w_input_treated) == names(w_input_control)) == length(w_input_control)
# check if there are zero-changes, add pseudocount if necessary
sum(w_input_treated == 0)
sum(w_input_control == 0)
foldchange_input <- log2(w_input_treated) - log2(w_input_control)


# look at individual genes
foldchange_input[order(abs(foldchange_input), decreasing=T)][1:50]
write.table(foldchange_input[order(abs(foldchange_input), decreasing=T)][1:50], file='top50_diff_log2fold.tsv', sep='\t', col.names = F, quote=F)


# Produce the native KEGG plot (PNG)
dme <- pathview(gene.data=foldchange_input, pathway.id="hsa04662", species = 'hsa') # B cell receptor signaling
dme <- pathview(gene.data=foldchange_input, pathway.id="hsa04210", species = 'hsa') # Apoptosis

```
